FROM python:3.9.16

WORKDIR /app

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python - --version 1.2.0 && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /
# COPY ./pyproject.toml /

# Allow installing dev dependencies to run tests
RUN bash -c "poetry update"
RUN bash -c "poetry install --no-root --no-dev"


COPY . .
ENV PYTHONPATH=/app