name: pyrmd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - babel
  - matplotlib
  - matplotlib-base
  - numpy
  - numpy-base
  - openbabel
  - pandas
  - rdkit
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  # - uvicorn==0.21.1
  # - fastapi==0.95.0
  # - pydantic==1.10.7
  # - python-multipart
  # - psutil==5.9.4


